image: baltig.infn.it:4567/epics-containers/epics-py-base

stages:
  - ophyd-test
  - pypi-publish


before_script:
  # Update pip to the latest version
  - python3 -m pip install --upgrade pip
  - pip install .
  - export PATH=$PATH:$HOME/.local/bin
  - ls $HOME/.local/lib/python3.10/site-packages/epik8s_tools/template/

ophyd-test:
  stage: ophyd-test
  script:
    - echo "to fill"


pypi-publish:
  stage: pypi-publish
  script:
    - python3 -m pip install --upgrade build twine
    # Build the package
    - python3 -m build
    # Publish to PyPI
    - python3 -m twine upload dist/* -u $PYPI_USERNAME -p $PYPI_TOKEN
  only:
    - main  # Optional: Restrict this stage to specific branches
  dependencies:
    - ophyd-test